### ISSUE TITLE
[Question] usage inside Xcode project

### ISSUE THREAD

**Issue by o15a3d4l11s2** [vinhnx/vintage#2]
We have an iOS app that uses a combination of SPM and Cocoapods. Is there a way to use the swift command to check for new SPM packages? The SPM dependencies are added as described here: https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app, so there is no Package.swift file inside out project.

**Comment by vinhnx** [comment]
Hi @o15a3d4l11s2 , I'm not sure if this helps `swift-outdated` https://github.com/kiliankoe/swift-outdated

**Comment by o15a3d4l11s2** [comment]
Hi @vinhnx, thanks for the update. I am happy to share that we discussed this with the creator of the project and this feature is now implemented in the latest version.
